### PR TITLE
fix mirror template

### PR DESCRIPTION
**Pull request by kalantar**
Mirror template should check for 0 weight for mirror and not attempt to configure mirroring in this case.

### CODE REVIEW

**Review by sriumcp — APPROVED** [review]
I feel the templates can be simplified significantly (and frankly, I don't follow the double-brace inside double-brace) construct.

In any case, lets get this in ... and revisit the simplifications later.

**Comment by kalantar** [comment]
> I feel the templates can be simplified significantly (and frankly, I don't follow the double-brace inside double-brace) construct.

Suggestions for simplification good. The double brace is escaped so as to embed `{{ if gt .Weight 0 }}` in the output `routingTemplate`.

**Review by sriumcp — APPROVED** [review]
lgtm

**Comment by sriumcp** [comment]
> The double brace is escaped so as to embed `{{ if gt .Weight 0 }}` in the output `routingTemplate`.

Ok, makes sense.

**Pull request merged**
