### PR TITLE
Fix bug where custom headers wouldn't make their way to iter8/fortio

### PR DESCRIPTION
**Pull request by dean-shaff**
We expect headers to be a nested object in an array of objects under the `versionInfo` section in the generated experiments.yaml file (see definition of `versionHTTP` struct [here](https://github.com/iter8-tools/iter8/blob/master/base/collect_http.go#L17)). 

Change `templates/_experiment.tpl` to ensure that headers get properly passed on to iter8 and fortio. 

We can test that custom headers don't get passed on by defining key value pairs in the `headers` section of `values.yaml` and subsequently running `iter8 run`. 

```yaml
headers:
  foo: bar 
```

### CODE REVIEW

**Comment by sriumcp** [comment]
Good catch re: indentation.

***

Could you please rebase your branch and push again, so that the tests pass on this PR? We just right in the middle of Iter8 v0.9 release which is cleaning up (and adding more) tests in the `iter8`, `hub` and `docs` repo.

**Comment by dean-shaff** [comment]
Just merged upstream changes!

**Comment by sriumcp** [comment]
Integration tests pass, which is great.

Could you also please [sign your commit](https://iter8.tools/0.8/contributing/#sign-your-commits). This will make the DCO check pass, which is all that we need to merge this PR.

**Review by sriumcp — CHANGES_REQUESTED** [review]
Could you please bump up the chart version in [`Chart.yaml`](https://github.com/iter8-tools/hub/blob/main/charts/load-test-http/Chart.yaml) to `0.1.1` from `0.1.0`? 

This ensures proper (Helm/Iter8 experiment) chart versioning.

**Comment by sriumcp** [comment]
@dean-shaff 

Latest release is now published at ... https://iter8.tools/0.9/

Your fix should work with this release. If the problem persists, please feel free to open a bug report.

***

Thanks a lot for tracking down the header issue.

**Pull request merged**
